site_name: Atheist World
site_url: https://atheistworld.github.io

markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 2
  - admonition
  - codehilite
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - sane_lists

theme:
  name: material

nav:
  - Home: index.md
  - Religious Texts:
      - Manusmriti:
          - Creation of Heaven and Earth: religious-texts/manusmriti/creation-of-heaven-and-earth.md
          - Creation of Brahmana and other Castes: religious-texts/manusmriti/creation-of-brahmana-and-other-castes.md
          - Creation of the Male and the Female: religious-texts/manusmriti/creation-of-male-and-female.md
          - Superiority of the Brahmana: religious-texts/manusmriti/superiority-of-brahmana.md
  - Disclaimer: disclaimer.md
